{
 "title": "nGLP Backtest",
 "time": { "from": "2023-02-09T17:52:26.489Z", "to": "2023-02-24T15:53:29.098Z" },
 "templating": {
  "list": [
   {
    "name": "strategy",
    "label": "Strategy",
    "query": "SHOW TAG VALUES FROM \"nglp_strategy\" WITH KEY = \"strategy\""
   }
  ]
 },
 "panels": [
  {
   "title": "totalAssets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nglp_strategy",
     "select": [
      [
       { "params": [ "totalAssets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Debt Ratios",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ETH",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nglp_strategy",
     "select": [
      [
       { "params": [ "btcDebtRatio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" }
     ]
    },
    {
     "alias": "BTC",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nglp_strategy",
     "select": [
      [
       { "params": [ "ethDebtRatio" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "ETH & BTC Prices",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "BTC",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nglp_strategy",
     "select": [
      [
       { "params": [ "btcPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" }
     ]
    },
    {
     "alias": "ETH",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nglp_strategy",
     "select": [
      [
       { "params": [ "ethPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "ETH & BTC Prices",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "BTC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nglp_strategy",
     "select": [
      [
       { "params": [ "btcPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" }
     ]
    },
    {
     "alias": "ETH",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "nglp_strategy",
     "select": [
      [
       { "params": [ "ethPrice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "GLP Rewards ($ETH)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Rewards ($)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "glp_position",
     "select": [
      [
       { "params": [ "rewards" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative Borrowing Costs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "BTC Borrow Fee ($)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gmx_position",
     "select": [
      [
       { "params": [ "borrowFee" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" },
      { "condition": "AND", "key": "shortToken", "operator": "=", "value": "BTC" }
     ]
    },
    {
     "alias": "ETH Borrow Fee ($)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "gmx_position",
     "select": [
      [
       { "params": [ "borrowFee" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "strategy", "operator": "=~", "value": "/^$strategy$/" },
      { "condition": "AND", "key": "shortToken", "operator": "=", "value": "ETH" }
     ]
    }
   ]
  }
 ]
}