{
 "title": "Struct Backtests",
 "time": { "from": "now-3M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "starttime",
    "label": "Start Time",
    "query": "SHOW TAG VALUES FROM \"struct_joesv2_summary\" WITH KEY = \"start\""
   },
   {
    "name": "symbol",
    "label": "Symbol",
    "query": "SHOW TAG VALUES FROM \"struct_joesv2\" WITH KEY = \"symbol\""
   },
   {
    "name": "fixedToken",
    "label": "Fixed Token",
    "query": "SHOW TAG VALUES FROM \"struct_joesv2\" WITH KEY = \"fixedToken\""
   }
  ]
 },
 "panels": [
  { "title": "Strategy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "APR",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "start" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" }
     ],
     "measurement": "struct_joes_autopool_summary",
     "select": [
      [
       { "params": [ "fixedApr" ], "type": "field" }
      ],
      [
       { "params": [ "variableApr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "symbol", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "fixedToken", "operator": "=~", "value": "/^$fixedToken$/" }
     ]
    }
   ]
  },
  {
   "title": "APR",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "start" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "rebalance" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" }
     ],
     "measurement": "struct_joesv2_summary",
     "select": [
      [
       { "params": [ "fixedApr" ], "type": "field" }
      ],
      [
       { "params": [ "variableApr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "start", "operator": "=~", "value": "/^$starttime$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "fixedToken", "operator": "=~", "value": "/^$fixedToken$/" }
     ]
    }
   ]
  },
  {
   "title": "Fixed & Variable Returns",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "[$tag_start] Fixed ($tag_base)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "base" ], "type": "tag" },
      { "params": [ "start" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "rebalance" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "struct_autopool",
     "select": [
      [
       { "params": [ "fixedReturns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "start", "operator": "=~", "value": "/^$starttime$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "fixedToken", "operator": "=~", "value": "/^$fixedToken$/" }
     ]
    },
    {
     "alias": "[$tag_start] Variable ($tag_quote)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "quote" ], "type": "tag" },
      { "params": [ "start" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "rebalance" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "struct_joesv2",
     "select": [
      [
       { "params": [ "variableReturns" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "start", "operator": "=~", "value": "/^$starttime$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "fixedToken", "operator": "=~", "value": "/^$fixedToken$/" }
     ]
    }
   ]
  },
  {
   "title": "Earnings",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "[$tag_start] Fixed ($tag_base)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "base" ], "type": "tag" },
      { "params": [ "start" ], "type": "tag" },
      { "params": [ "rebalance" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "struct_autopool",
     "select": [
      [
       { "params": [ "fixedApr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "start", "operator": "=~", "value": "/^$starttime$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "fixedToken", "operator": "=~", "value": "/^$fixedToken$/" }
     ]
    },
    {
     "alias": "[$tag_start] Variable ($tag_quote)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "quote" ], "type": "tag" },
      { "params": [ "start" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "rebalance" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "struct_joesv2",
     "select": [
      [
       { "params": [ "variableApr" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "start", "operator": "=~", "value": "/^$starttime$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "fixedToken", "operator": "=~", "value": "/^$fixedToken$/" }
     ]
    }
   ]
  },
  {
   "title": "Prices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "$tag_base / $tag_quote",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "start" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "struct_joes_autopool",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "start", "operator": "=~", "value": "/^$starttime$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$symbol$/" }
     ]
    }
   ]
  },
  { "title": "Position", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Value (In quote)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "alias": "[$tag_start] $tag_quote",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "quote" ], "type": "tag" },
      { "params": [ "start" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "rebalance" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "struct_joes_autopool",
     "select": [
      [
       { "params": [ "valueInQuote" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "start", "operator": "=~", "value": "/^$starttime$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "fixedToken", "operator": "=~", "value": "/^$fixedToken$/" }
     ]
    }
   ]
  },
  {
   "title": "Value (In base)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "alias": "[$tag_start] Base Value ($tag_quote)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "quote" ], "type": "tag" },
      { "params": [ "start" ], "type": "tag" },
      { "params": [ "symbol" ], "type": "tag" },
      { "params": [ "rebalance" ], "type": "tag" },
      { "params": [ "fixedToken" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "struct_joes_autopool",
     "select": [
      [
       { "params": [ "valueInBase" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "start", "operator": "=~", "value": "/^$starttime$/" },
      { "condition": "AND", "key": "symbol", "operator": "=~", "value": "/^$symbol$/" },
      { "condition": "AND", "key": "fixedToken", "operator": "=~", "value": "/^$fixedToken$/" }
     ]
    }
   ]
  }
 ]
}